"""Destination information service with comprehensive travel data."""

DESTINATIONS = [
    {
        "id": "dest-barcelona",
        "name": "Barcelona",
        "country": "Spain",
        "continent": "Europe",
        "description": "A vibrant coastal city famous for Gaudi's architecture, amazing food, beautiful beaches, and an electric nightlife scene. Perfect for culture lovers and party-goers alike.",
        "image_url": "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
        "avg_flight_price_gbp": 80,
        "avg_hotel_price_gbp": 80,
        "avg_daily_cost_gbp": 65,
        "best_months": ["May", "Jun", "Sep", "Oct"],
        "highlights": ["Sagrada Familia", "Park Guell", "La Rambla", "Gothic Quarter", "Barceloneta Beach", "Camp Nou"],
        "currency": "EUR",
        "language": "Spanish/Catalan",
        "timezone": "CET (UTC+1)",
        "visa_required": False,
        "safety_rating": 8.2,
        "latitude": 41.3851,
        "longitude": 2.1734,
    },
    {
        "id": "dest-paris",
        "name": "Paris",
        "country": "France",
        "continent": "Europe",
        "description": "The City of Light enchants with world-class art, iconic landmarks, exquisite cuisine, and romantic boulevards. A must-visit for culture, history, and gastronomy.",
        "image_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        "avg_flight_price_gbp": 100,
        "avg_hotel_price_gbp": 100,
        "avg_daily_cost_gbp": 85,
        "best_months": ["May", "Jun", "Sep"],
        "highlights": ["Eiffel Tower", "Louvre Museum", "Notre-Dame", "Montmartre", "Champs-Elysees", "Versailles"],
        "currency": "EUR",
        "language": "French",
        "timezone": "CET (UTC+1)",
        "visa_required": False,
        "safety_rating": 7.8,
        "latitude": 48.8566,
        "longitude": 2.3522,
    },
    {
        "id": "dest-rome",
        "name": "Rome",
        "country": "Italy",
        "continent": "Europe",
        "description": "The Eternal City blends ancient history with vibrant modern life. Explore ruins, toss coins in fountains, and devour the world's best pizza and pasta.",
        "image_url": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        "avg_flight_price_gbp": 90,
        "avg_hotel_price_gbp": 90,
        "avg_daily_cost_gbp": 70,
        "best_months": ["Apr", "May", "Sep", "Oct"],
        "highlights": ["Colosseum", "Vatican City", "Trevi Fountain", "Pantheon", "Roman Forum", "Trastevere"],
        "currency": "EUR",
        "language": "Italian",
        "timezone": "CET (UTC+1)",
        "visa_required": False,
        "safety_rating": 8.0,
        "latitude": 41.9028,
        "longitude": 12.4964,
    },
    {
        "id": "dest-amsterdam",
        "name": "Amsterdam",
        "country": "Netherlands",
        "continent": "Europe",
        "description": "Charming canals, world-class museums, cycling culture, and a liberal atmosphere make Amsterdam one of Europe's most unique and enjoyable cities.",
        "image_url": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
        "avg_flight_price_gbp": 85,
        "avg_hotel_price_gbp": 95,
        "avg_daily_cost_gbp": 75,
        "best_months": ["May", "Jun", "Jul", "Aug"],
        "highlights": ["Anne Frank House", "Rijksmuseum", "Van Gogh Museum", "Canal Ring", "Vondelpark", "Jordaan"],
        "currency": "EUR",
        "language": "Dutch",
        "timezone": "CET (UTC+1)",
        "visa_required": False,
        "safety_rating": 8.5,
        "latitude": 52.3676,
        "longitude": 4.9041,
    },
    {
        "id": "dest-lisbon",
        "name": "Lisbon",
        "country": "Portugal",
        "continent": "Europe",
        "description": "Sun-drenched hills, colorful tiles, vintage trams, and incredible seafood. Lisbon offers amazing value with a laid-back Mediterranean vibe.",
        "image_url": "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800",
        "avg_flight_price_gbp": 70,
        "avg_hotel_price_gbp": 65,
        "avg_daily_cost_gbp": 50,
        "best_months": ["May", "Jun", "Sep", "Oct"],
        "highlights": ["Belem Tower", "Alfama", "Time Out Market", "Tram 28", "Sintra Day Trip", "Pasteis de Nata"],
        "currency": "EUR",
        "language": "Portuguese",
        "timezone": "WET (UTC+0)",
        "visa_required": False,
        "safety_rating": 8.7,
        "latitude": 38.7223,
        "longitude": -9.1393,
    },
    {
        "id": "dest-dubai",
        "name": "Dubai",
        "country": "UAE",
        "continent": "Asia",
        "description": "A futuristic desert metropolis with record-breaking skyscrapers, luxury shopping, stunning beaches, and world-class entertainment.",
        "image_url": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
        "avg_flight_price_gbp": 250,
        "avg_hotel_price_gbp": 100,
        "avg_daily_cost_gbp": 90,
        "best_months": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "highlights": ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari", "Gold Souk", "Dubai Marina"],
        "currency": "AED",
        "language": "Arabic/English",
        "timezone": "GST (UTC+4)",
        "visa_required": False,
        "safety_rating": 9.2,
        "latitude": 25.2048,
        "longitude": 55.2708,
    },
    {
        "id": "dest-bangkok",
        "name": "Bangkok",
        "country": "Thailand",
        "continent": "Asia",
        "description": "A sensory overload of ornate temples, bustling street markets, incredible street food, and vibrant nightlife. Amazing value for money.",
        "image_url": "https://images.unsplash.com/photo-1508009603885-50cf7c8a1ee8?w=800",
        "avg_flight_price_gbp": 350,
        "avg_hotel_price_gbp": 35,
        "avg_daily_cost_gbp": 30,
        "best_months": ["Nov", "Dec", "Jan", "Feb"],
        "highlights": ["Grand Palace", "Wat Pho", "Chatuchak Market", "Street Food", "Khao San Road", "Floating Markets"],
        "currency": "THB",
        "language": "Thai",
        "timezone": "ICT (UTC+7)",
        "visa_required": False,
        "safety_rating": 7.5,
        "latitude": 13.7563,
        "longitude": 100.5018,
    },
    {
        "id": "dest-newyork",
        "name": "New York",
        "country": "USA",
        "continent": "North America",
        "description": "The city that never sleeps! Iconic skyline, Broadway shows, incredible food scene, world-class museums, and energy like nowhere else.",
        "image_url": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
        "avg_flight_price_gbp": 350,
        "avg_hotel_price_gbp": 140,
        "avg_daily_cost_gbp": 110,
        "best_months": ["May", "Jun", "Sep", "Oct"],
        "highlights": ["Statue of Liberty", "Central Park", "Times Square", "Brooklyn Bridge", "Broadway", "MoMA"],
        "currency": "USD",
        "language": "English",
        "timezone": "EST (UTC-5)",
        "visa_required": False,
        "safety_rating": 7.5,
        "latitude": 40.7128,
        "longitude": -74.0060,
    },
    {
        "id": "dest-tokyo",
        "name": "Tokyo",
        "country": "Japan",
        "continent": "Asia",
        "description": "A fascinating blend of ultra-modern and traditional. From neon-lit streets to serene temples, Tokyo is an unforgettable experience.",
        "image_url": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
        "avg_flight_price_gbp": 400,
        "avg_hotel_price_gbp": 80,
        "avg_daily_cost_gbp": 75,
        "best_months": ["Mar", "Apr", "Oct", "Nov"],
        "highlights": ["Shibuya Crossing", "Senso-ji Temple", "Akihabara", "Tsukiji Market", "Mt Fuji Day Trip", "Harajuku"],
        "currency": "JPY",
        "language": "Japanese",
        "timezone": "JST (UTC+9)",
        "visa_required": False,
        "safety_rating": 9.5,
        "latitude": 35.6762,
        "longitude": 139.6503,
    },
    {
        "id": "dest-bali",
        "name": "Bali",
        "country": "Indonesia",
        "continent": "Asia",
        "description": "Tropical paradise with stunning temples, lush rice terraces, beautiful beaches, and a thriving wellness scene. Incredible value.",
        "image_url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
        "avg_flight_price_gbp": 400,
        "avg_hotel_price_gbp": 35,
        "avg_daily_cost_gbp": 25,
        "best_months": ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
        "highlights": ["Ubud Rice Terraces", "Uluwatu Temple", "Seminyak Beach", "Mount Batur", "Nusa Penida", "Tanah Lot"],
        "currency": "IDR",
        "language": "Indonesian",
        "timezone": "WITA (UTC+8)",
        "visa_required": False,
        "safety_rating": 8.0,
        "latitude": -8.3405,
        "longitude": 115.0920,
    },
    {
        "id": "dest-cancun",
        "name": "Cancun",
        "country": "Mexico",
        "continent": "North America",
        "description": "Crystal-clear Caribbean waters, ancient Mayan ruins, vibrant nightlife, and all-inclusive resorts. Perfect for beach lovers and history buffs.",
        "image_url": "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=800",
        "avg_flight_price_gbp": 400,
        "avg_hotel_price_gbp": 70,
        "avg_daily_cost_gbp": 60,
        "best_months": ["Dec", "Jan", "Feb", "Mar", "Apr"],
        "highlights": ["Chichen Itza", "Isla Mujeres", "Cenotes", "Tulum", "Xcaret", "Playa del Carmen"],
        "currency": "MXN",
        "language": "Spanish",
        "timezone": "EST (UTC-5)",
        "visa_required": False,
        "safety_rating": 7.0,
        "latitude": 21.1619,
        "longitude": -86.8515,
    },
    {
        "id": "dest-capetown",
        "name": "Cape Town",
        "country": "South Africa",
        "continent": "Africa",
        "description": "Stunning natural beauty where mountains meet the ocean. Wine country, safari opportunities, vibrant culture, and incredible value.",
        "image_url": "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800",
        "avg_flight_price_gbp": 400,
        "avg_hotel_price_gbp": 50,
        "avg_daily_cost_gbp": 40,
        "best_months": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "highlights": ["Table Mountain", "Cape of Good Hope", "Boulders Beach", "V&A Waterfront", "Wine Route", "Robben Island"],
        "currency": "ZAR",
        "language": "English/Afrikaans",
        "timezone": "SAST (UTC+2)",
        "visa_required": False,
        "safety_rating": 6.5,
        "latitude": -33.9249,
        "longitude": 18.4241,
    },
    {
        "id": "dest-marrakech",
        "name": "Marrakech",
        "country": "Morocco",
        "continent": "Africa",
        "description": "An exotic adventure of vibrant souks, stunning palaces, aromatic spices, and incredible riads. A feast for all the senses.",
        "image_url": "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800",
        "avg_flight_price_gbp": 100,
        "avg_hotel_price_gbp": 40,
        "avg_daily_cost_gbp": 30,
        "best_months": ["Mar", "Apr", "May", "Oct", "Nov"],
        "highlights": ["Jemaa el-Fna", "Bahia Palace", "Majorelle Garden", "Medina Souks", "Atlas Mountains", "Sahara Day Trip"],
        "currency": "MAD",
        "language": "Arabic/French",
        "timezone": "WET (UTC+0)",
        "visa_required": False,
        "safety_rating": 7.2,
        "latitude": 31.6295,
        "longitude": -7.9811,
    },
    {
        "id": "dest-singapore",
        "name": "Singapore",
        "country": "Singapore",
        "continent": "Asia",
        "description": "A futuristic city-state with incredible food, stunning gardens, luxury shopping, and a fascinating blend of cultures.",
        "image_url": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
        "avg_flight_price_gbp": 350,
        "avg_hotel_price_gbp": 80,
        "avg_daily_cost_gbp": 70,
        "best_months": ["Feb", "Mar", "Jul", "Aug"],
        "highlights": ["Gardens by the Bay", "Marina Bay Sands", "Sentosa Island", "Hawker Centres", "Orchard Road", "Little India"],
        "currency": "SGD",
        "language": "English/Mandarin/Malay/Tamil",
        "timezone": "SGT (UTC+8)",
        "visa_required": False,
        "safety_rating": 9.7,
        "latitude": 1.3521,
        "longitude": 103.8198,
    },
    {
        "id": "dest-maldives",
        "name": "Maldives",
        "country": "Maldives",
        "continent": "Asia",
        "description": "Ultimate tropical paradise with overwater villas, crystal-clear lagoons, world-class diving, and some of the most beautiful beaches on Earth.",
        "image_url": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
        "avg_flight_price_gbp": 450,
        "avg_hotel_price_gbp": 120,
        "avg_daily_cost_gbp": 80,
        "best_months": ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
        "highlights": ["Overwater Villas", "Snorkelling", "Diving", "Sunset Cruises", "Spa Retreats", "Sandbank Picnics"],
        "currency": "MVR",
        "language": "Dhivehi/English",
        "timezone": "MVT (UTC+5)",
        "visa_required": False,
        "safety_rating": 8.8,
        "latitude": 3.2028,
        "longitude": 73.2207,
    },
    {
        "id": "dest-iceland",
        "name": "Reykjavik",
        "country": "Iceland",
        "continent": "Europe",
        "description": "Land of fire and ice with stunning glaciers, geysers, hot springs, northern lights, and dramatic volcanic landscapes.",
        "image_url": "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800",
        "avg_flight_price_gbp": 120,
        "avg_hotel_price_gbp": 120,
        "avg_daily_cost_gbp": 100,
        "best_months": ["Jun", "Jul", "Aug", "Sep"],
        "highlights": ["Blue Lagoon", "Northern Lights", "Golden Circle", "Whale Watching", "Glacier Hiking", "Geysir"],
        "currency": "ISK",
        "language": "Icelandic/English",
        "timezone": "GMT (UTC+0)",
        "visa_required": False,
        "safety_rating": 9.8,
        "latitude": 64.1466,
        "longitude": -21.9426,
    },
]


def get_popular_destinations(limit: int = 12) -> list[dict]:
    return DESTINATIONS[:limit]


def get_destination_info(name: str) -> dict | None:
    name_lower = name.lower()
    for dest in DESTINATIONS:
        if dest["name"].lower() == name_lower or dest["country"].lower() == name_lower:
            return dest
    return None


def search_destinations(query: str = "", continent: str = "", max_daily_cost: float = 0) -> list[dict]:
    results = DESTINATIONS
    if query:
        q = query.lower()
        results = [d for d in results if q in d["name"].lower() or q in d["country"].lower() or q in d["description"].lower()]
    if continent:
        c = continent.lower()
        results = [d for d in results if d["continent"].lower() == c]
    if max_daily_cost > 0:
        results = [d for d in results if (d.get("avg_daily_cost_gbp") or 999) <= max_daily_cost]
    return results
